### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by nguyen179son** [YtoTech/latex-on-http#6]
![Screenshot from 2019-11-29 22-52-29](https://user-images.githubusercontent.com/28885479/69891188-ee752500-12fa-11ea-855d-e7145c29e79c.png)
Is the server down atm?

**Comment by MonsieurV** [comment]
Hello @nguyen179son,

No, the service is not down. Howerver there seems to be an error with the payload you intend to compile.

I'll try to look at the logs.

**Comment by MonsieurV** [comment]
Re,

I've looked at the logs. The issue is that:
* one of the file URL you provide is not openly accessible (it gives a 403 forbidden error)
* the Latex-on-HTTP service is crashing on this fetch error, instead of properly reporting it back to you

This is a bit strange however, because I succeed to access the URL with my browser and by doing a wget on it, so I'm not sure why the web server is denying access to the Latex-on-HTTP service. 
Maybe there is rate limiting by IP? I've tested a wget from the server used by the service, and it is indeed blocked, so this may be that.

**Comment by MonsieurV** [comment]
For the HTTP-on-Latex service, I can make an update to provide back a clear error message when file fetch by URL are failing (HTTP errors: 403, 404, etc.)

For your specific issue of rate-limiting, I can't do much.
You can pass the file content yourself directly instead of passing an URL, if that is a possibility for you.

There aren't much examples of that in the doc for now, but you can look at [this sample](https://github.com/YtoTech/latex-on-http/tree/master/examples/gitlab_ci) which show how to pass a local file directly in the payload (by [doing a base64 of the file](https://github.com/YtoTech/latex-on-http/blob/master/examples/gitlab_ci/compile.sh#L5)).
You can reach me at the mail in my profile to see how to make it work in your case. :)

**Comment by MonsieurV** [comment]
A proper response should now be reported by the Latex-on-HTTP API when a file fetch error occurs.

Eg.: [see test_fetchers.py](https://github.com/YtoTech/latex-on-http/blob/master/tests/test_fetchers.py#L14)
